### ISSUE TITLE
Problem on raspberry pi 3B  stretch 

### ISSUE THREAD

**Issue by johnnewto** [guh/nymea-networkmanager#10]
Great Project thanks: I've followed the instructions but get the following error. 

 I | Application: =====================================
 I | Application: Starting nymea-networkmanager "0.3.2"
 I | Application: =====================================
 I | Application: Advertising name: "BT WLAN setup"
 I | Application: Platform name: "nymea-box"
 I | Application: Mode: Core::Mode(ModeOffline)
 I | Application: Timeout: 60
 W | NymeaService: Invalid D-Bus HardwareManager interface.
 W | NymeaService: Could not init nymea D-Bus services
 W | NetworkManager: Invalid DBus network manager interface. NetworkManagre not available.
 W | Application: Could not start network manager. Please make sure the networkmanager is available.
^C I | Application: Cought SIGINT quit signal...
 I | Application: =====================================
 I | Application: Shutting down nymea-networkmanager
 I | Application: =====================================
 I | Application: Shutting down nymea service
 I | Application: Shutting down bluetooth service
 I | Application: Shutting down network-manager service

**Comment by t-mon** [comment]
Hello! 
It looks like you have not installed the network-manager application. The daemon is taking to the network-manager using D-Bus, but he cannot find any available network-manager D-Bus interface.  
Which kind of system are you using?
Is the network-manager installed?
Are you running the daemon as root or user?

**Comment by johnnewto** [comment]
Thanks for your comments. 
It's a raspberry pi running stretch.

I've installed network-manager by following 
https://raspberrypi.stackexchange.com/questions/29783/how-to-setup-network-manager-on-raspbian
and it is operating OK on both wifi and ethernet.

the response is now better but still a couple of errors, 
I'm running the daemon as user

pi@raspberrypi:~/Documents/berrylan/nymea-networkmanager/build $ sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/libnymea-networkmanager/ ./nymea-networkmanager/nymea-networkmanager
 I | Application: =====================================
 I | Application: Starting nymea-networkmanager "0.3.2"
 I | Application: =====================================
 I | Application: Advertising name: "BT WLAN setup"
 I | Application: Platform name: "nymea-box"
 I | Application: Mode: Core::Mode(ModeOffline)
 I | Application: Timeout: 60
 W | NymeaService: Invalid D-Bus HardwareManager interface.
 W | NymeaService: Could not init nymea D-Bus services
 I | Application: NetworkManager::NetworkManagerState(NetworkManagerStateConnectedGlobal)
 I | Application: Networkmanager networking is now enabled
 I | Application: Networkmanager wireless networking is now enabled
 I | Application: Init is running
 I | Application: Post run service

**Comment by johnnewto** [comment]
I was trying to get berrylan working and thought this was the server to use. i was following the wrong instructions. Instead used the berrylan instructions and now berrylan is connecting via BT & wifi etc.  Many thanks . John

https://github.com/guh/berrylan

**Comment by t-mon** [comment]
I'm glad that it works now :) 

The following warning can be ignored:

    W | NymeaService: Invalid D-Bus HardwareManager interface.
    W | NymeaService: Could not init nymea D-Bus services 

The daemon was designed to work together with our IoT middle war nymea (https://nymea.io), and tells you that it could not be found. This has no influence on the Wifi setup behavior.
