### ISSUE TITLE
Changing MAC address on each boot?

### ISSUE THREAD

**Issue by Blizzke** [guh/nymea-networkmanager#11]
Why does the network manager change the Wifi MAC address on each boot?
My home network uses the MAC address to identify devices and allow access (and assign fixed IPs) and now I can't actually use that anymore. Is there a way to disable this behavior?

**Comment by igorpecovnik** [comment]
https://fedoramagazine.org/randomize-mac-address-nm/
and
wifi.scan-rand-mac-address=no

should do the trick.

**Comment by Blizzke** [comment]
So basically this networkmanager lies on top of the original one then? Probably the reason I couldn't find anything about it.

**Comment by t-mon** [comment]
yes, the nymea-networkmanager is basically a D-Bus client to the original network-manager providing the Bluetooth LE API for configuration.

**Comment by Blizzke** [comment]
Now that I read up about the randomize functionality and know I can keep it default for my own network but have it randomized for others I really like it. Guess that solves my question. Thanks for the help everyone!
