### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by logidelic** [guh/nymea-networkmanager#4]
Thank you for this interesting project. I am trying to test it out on an Nvidia TX2. Unfortunately, the pre-built library errors with `version 'Qt_5' not found` (even though it is finding the correct qt5 .so files). I'm guessing that the easiest solution is to rebuild nymea-networkmanager and link against my installed qt5 library.

How can I rebuild? Are there instructions somewhere (I read the docs but couldn't find it...).

**Comment by t-mon** [comment]
Hi! Sorry for the late response, the notification got lost.
The build process depends a little bit on you operating system. For debian based systems you need following build packages:
`qtbase5-dev` `qtbase5-dev-tools` `libqt5bluetooth5` `qtconnectivity5-dev` `git`

The clone the git repository and change to the source directory.

    $ mkdir build
    $ cd build
    $ qmake ..
    $ make -j`nproc`

Hope this helps! Please let me know if it worked, then I'll write it into the README.md file.
Thanks :)
